#!/usr/bin/env ruby

script = <<-APPLESCRIPT
  tell application "System Events"
    set activeApps to name of application processes whose frontmost is true
    set activeApp to item 1 of activeApps
  end tell
  set myPath to #{ARGV[0].inspect}
  try
    do shell script "rm ~/Documents/mutt-html-alternative.html"
  end try
  tell application "Marked"
    activate
    open myPath
  end tell
  tell application "System Events"
    keystroke "s" using command down
    keystroke "g" using {command down, shift down}
    delay 1
    keystroke "~/Documents"
    keystroke return
    delay 2
    keystroke "mutt-html-alternative"
    keystroke return
    keystroke "w" using command down
  end tell
  tell application activeApp to activate
APPLESCRIPT

alt = File.expand_path('~/Documents/mutt-html-alternative.html')
File.unlink alt if File.exist?(alt)

IO.popen('osascript', 'w+') do |f|
  f.puts script
  f.flush
end
