#!/usr/bin/env ruby

begin
  require 'mail'
rescue LoadError
  warn 'Install the mail gem to have proper multipart/alternative support'
  exec 'msmtp', *ARGV
end

mail = Mail.new($stdin.read)

if mail.parts.map(&:filename).include?('mutt-html-alternative.html')
  new_mail = Mail.new
  new_mail.header = mail.header.to_s

  mail.parts.each do |part|
    if part.content_type =~ %r{^text/plain}
      new_mail.text_part = part
    elsif part.filename == 'mutt-html-alternative.html'
      new_mail.html_part = part
    #elsif !part.filename.nil? && part.filename != ''
    else
      new_mail.add_part part
    end
  end
else
  new_mail = mail
end

# File.open('/tmp/message.tmp', 'w+') { |f| f.puts new_mail.encoded.to_lf }

IO.popen(['msmtp', *ARGV], 'w+', :err => :out) do |f|
  f.puts new_mail.encoded.to_lf
  f.flush
end

IO.popen(['muttqt', '-f'], 'w+', :err => :out) do |f|
  f.puts new_mail.encoded.to_lf
  f.flush
end
