require 'erb'

class Context
  def self.new
    super.__get_binding
  end

  def __get_binding
    binding
  end
end

desc 'Install mac specific items'
task :install do
  puts 'installing wezTermHotkey'
  system 'clang', '-Os', '-fobjc-arc', '-framework', 'Carbon', '-framework',
         'AppKit', 'wezTermHotkey.m', '-o', File.expand_path('~/.bin/wezTermHotkey')

  loaded = Hash[`launchctl list`.strip.lines.map do |line|
    line = line.split
    [line.last, true]
  end]

  launch_agents_path = File.expand_path('~/Library/LaunchAgents')
  Dir.mkdir launch_agents_path unless Dir.exist? launch_agents_path

  Dir['im.ceh.*.plist*'].each do |plist|
    if plist =~ /\.erb$/
      contents = ERB.new(File.read(plist)).result(Context.new)
      plist = File.basename(plist).sub(/\.erb$/, '')
    else
      contents = File.read(plist, mode: 'rb')
    end
    dest = File.expand_path("~/Library/LaunchAgents/#{plist}")

    puts "installing #{plist} to ~/Library/LaunchAgents"
    File.write(dest, contents)

    if loaded[File.basename(dest, '.plist')]
      puts "shutting down #{plist}"
      system 'launchctl', 'unload', '-w', dest
    end

    puts "loading #{plist}"
    system 'launchctl', 'load', '-w', dest
  end
end
